Add ability to deploy against mainnet

diff --git a/medit b/medit
--- a/medit
+++ b/medit
@@ -93,6 +93,21 @@ function command_hack {
     fi
 }
 
+function command_live {
+    printf "${GREEN}The present tense made him nervous...${NC}\n"
+
+    # catch unexpected failures, do cleanup and output an error message
+    trap 'cleanup-live ; printf "${RED}docker-compose Failed For Unexpected Reasons${NC}\n"'\
+         HUP INT QUIT PIPE TERM
+
+    live-api
+    
+    if [ $? -ne 0 ] ; then
+        printf "${RED}Docker Compose Failed${NC}\n"
+        exit -1
+    fi
+}
+
 function command_down {
      printf "${GREEN}Killing docker instances${NC}\n"
      cleanup-hack;
